### ISSUE TITLE
Error: invalid attribute: version (nil)

### ISSUE THREAD

**Issue by aaronz8** [Mashape/homebrew-kong#6]
```
brew install kong --debug                                                                                     ⏎ ✱
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/mashape/homebrew-kong/Formula/kong.rb
Error: invalid attribute: version (nil)
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula.rb:160:in `validate_attributes!'
/usr/local/Library/Homebrew/formula.rb:118:in `initialize'
/usr/local/Library/Homebrew/formulary.rb:66:in `new'
/usr/local/Library/Homebrew/formulary.rb:66:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:176:in `factory'
/usr/local/Library/Homebrew/formulary.rb:316:in `find_with_priority'
/usr/local/Library/Homebrew/extend/ARGV.rb:20:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:127:in `<main>'
```

**Comment by aaronz8** [comment]
```
brew install kong --HEAD --debug                                                                                ✱
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/mashape/homebrew-kong/Formula/kong.rb
Error: undefined method `head?' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/pkg_version.rb:16:in `initialize'
/usr/local/Library/Homebrew/formula.rb:323:in `new'
/usr/local/Library/Homebrew/formula.rb:323:in `installed_prefix'
/usr/local/Library/Homebrew/formula.rb:300:in `installed?'
/usr/local/Library/Homebrew/cmd/install.rb:72:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:127:in `<main>'
```

**Comment by thibaultCha** [comment]
Cannot reproduce. Please run brew doctor or eventually report the bug where suggested.

**Comment by aaronz8** [comment]
hmm, brew doctor returns "Your system is ready to brew." and everything else I've installed seems to work fine. I'll update here if I find the issue.

**Comment by aaronz8** [comment]
A few coworkers also tried to install and got the same issue. Can you try again?

**Comment by thibaultCha** [comment]
My bad, I did not update the Formula before installing it. Pretty sure this comes from [this change](https://github.com/Mashape/homebrew-kong/pull/5/files).

**Comment by thibaultCha** [comment]
I just updated the Formula to Kong 0.4.2, could you give it a try?

**Comment by aaronz8** [comment]
it works! :) Thanks for the quick help.
